### ISSUE TITLE
1차 멘토링

### ISSUE THREAD

**Issue by wonchan9999** [Stockholic2022/Industrial_stockholic#19]
실시간으로 주가를 가져오는 프로젝트를 하려고 하는데 
프로젝트와 관련해서 멘토 분과 이야기

**Comment by wonchan9999** [comment]
멘토분께선 프로젝트가 굉장히 어려워 보이는데 할 수 있을까? 우려하심

**Comment by sincheol** [comment]
앱의 빠른 반응성을 위해 flutter 플랫폼 추천 해주심

**Comment by pdm7817** [comment]
pandas가 주식을 위해 만들어진 것이라고 알려주심

**Comment by sincheol** [comment]
백엔드는 다루기 쉬운걸로

**Comment by sincheol** [comment]
요구사항 분석서의 범위를 줄이고 거기에 집중 구현이 필요

**Comment by sincheol** [comment]
현업에서는 매매기법의 적용을 분기 단위가 잘된다고 알려져있음

**Comment by pdm7817** [comment]
평가 방식도 1분기로 정해주심

**Comment by wonchan9999** [comment]
알겠습니다~
