### ISSUE TITLE
회원 가입을 할 때

### ISSUE THREAD

**Issue by wonchan9999** [Stockholic2022/Industrial_stockholic#27]
회원 가입을 할 때, 아이디와 패스워드 말고 다른 것도 추가 인증을 해야 하나

**Comment by pdm7817** [comment]
아이디와 패스워드만 만들게 되면 한 사람이 여러 계정을 만들 수 있기 때문에 별로 좋지 않아보입니다.
따라서 추가 인증이 있으면 좋을 것 같습니다.
