### ISSUE TITLE
python의 문제점인 느린 반응성

### ISSUE THREAD

**Issue by sincheol** [Stockholic2022/Industrial_stockholic#30]
을 대체할만한 플랫폼이나 방안이 있나요

**Comment by sincheol** [comment]
여러 자문을 들어본 결과 flutter라는 플랫폼이 있네요

**Comment by sincheol** [comment]
flutter가 learning curve라는 단점이 있지만 프로젝트와 잘 맞는것 같습니다.

**Comment by sincheol** [comment]
그럼 flutter로 하겠습니다.

**Comment by wonchan9999** [comment]
flutter라는 플랫폼이 저도 좋아보입니다
