### ISSUE TITLE
로그인구현할 때 API를 활용할껀가

### ISSUE THREAD

**Issue by wonchan9999** [Stockholic2022/Industrial_stockholic#33]
카카오 api, 구글 api 등을 사용해서 로그인기능을 만들까요

**Comment by pdm7817** [comment]
FIREBASE의 기능을 보니까 인증만 되면 생각보다 쉽게 연동이 될 것 같습니다.

**Comment by sincheol** [comment]
네 firebase가 더 좋은것 같아요 향후 인증을 위해서
